services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: samkapandbl2/devops-for-programmers-project-74:latest
    container_name: devops-for-progs
    working_dir: /app
    ports:
      - "8080:8080"
    command: make test