FROM node:20.12.2
RUN pwd
RUN ls -la
WORKDIR /app
RUN pwd
RUN ls -la
COPY app/package.json package.json
COPY app/package-lock.json package-lock.json
RUN ls -la
RUN npm ci

COPY app/. .

EXPOSE 8080
ENV NODE_ENV=production
RUN make build

CMD ["make", "start"]