on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run tests
        run: make ci

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.production
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-for-programmers-project-74:latest