on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: make ci
  deploy:
    name: Build and push to docker
    needs: test
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile.production
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-for-programmers-project-74:latest